spring:
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        erbadagang-input:
          destination: ERBADAGANG-TOPIC-01 # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
          group: erbadagang-consumer-group-ERBADAGANG-TOPIC-01 # 消费者分组,命名规则：组名+topic名

        trek-input:
          destination: TREK-TOPIC-01 # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
          group: trek-consumer-group-TREK-TOPIC-01 # 消费者分组,命名规则：组名+topic名
        rocketmq:
          binder:
            name-server: 127.0.0.1:9876 # RocketMQ Namesrv 地址
          bindings:
            erbadagang-input:
              # RocketMQ Consumer 配置项，对应 RocketMQConsumerProperties 类
              consumer:
                enabled: true # 是否开启消费，默认为 true
                broadcasting: false # 是否使用广播消费，默认为 false 使用集群消费，如果要使用广播消费值设成true。

#-----------------------------------------mybatis-plus映射xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
